/* A RapidNet application. Generated by RapidNet compiler. */

#include "sdn-arp.h"
#include <cstdlib>
#include "ns3/nstime.h"
#include "ns3/simulator.h"
#include "ns3/type-ids.h"
#include "ns3/rapidnet-types.h"
#include "ns3/rapidnet-utils.h"
#include "ns3/assignor.h"
#include "ns3/selector.h"
#include "ns3/rapidnet-functions.h"

using namespace std;
using namespace ns3;
using namespace ns3::rapidnet;
using namespace ns3::rapidnet::sdnarp;

const string SdnArp::ARPMAPPING = "arpMapping";
const string SdnArp::ARPREPLY = "arpReply";
const string SdnArp::ARPREPLYCTL = "arpReplyCtl";
const string SdnArp::ARPREQCTL = "arpReqCtl";
const string SdnArp::ARPREQUEST = "arpRequest";
const string SdnArp::FLOWENTRY = "flowEntry";
const string SdnArp::HOSTPOS = "hostPos";
const string SdnArp::LINKHST = "linkHst";
const string SdnArp::LINKSWC = "linkSwc";
const string SdnArp::OFCONNCTL = "ofconnCtl";
const string SdnArp::OFCONNSWC = "ofconnSwc";
const string SdnArp::PACKET = "packet";
const string SdnArp::PACKETIN = "packetIn";
const string SdnArp::PACKETOUT = "packetOut";
const string SdnArp::RH2PACKETHOST = "rh2packetHost";

NS_LOG_COMPONENT_DEFINE ("SdnArp");
NS_OBJECT_ENSURE_REGISTERED (SdnArp);

TypeId
SdnArp::GetTypeId (void)
{
  static TypeId tid = TypeId ("ns3::rapidnet::sdnarp::SdnArp")
    .SetParent<RapidNetApplicationBase> ()
    .AddConstructor<SdnArp> ()
    ;
  return tid;
}

SdnArp::SdnArp()
{
  NS_LOG_FUNCTION_NOARGS ();
}

SdnArp::~SdnArp()
{
  NS_LOG_FUNCTION_NOARGS ();
}

void
SdnArp::DoDispose (void)
{
  NS_LOG_FUNCTION_NOARGS ();

  RapidNetApplicationBase::DoDispose ();
}

void
SdnArp::StartApplication (void)
{
  NS_LOG_FUNCTION_NOARGS ();

  RapidNetApplicationBase::StartApplication ();
  RAPIDNET_LOG_INFO("SdnArp Application Started");
}

void
SdnArp::StopApplication ()
{
  NS_LOG_FUNCTION_NOARGS ();

  RapidNetApplicationBase::StopApplication ();
  RAPIDNET_LOG_INFO("SdnArp Application Stopped");
}

void
SdnArp::InitDatabase ()
{
  //RapidNetApplicationBase::InitDatabase ();

  AddRelationWithKeys (ARPMAPPING, attrdeflist (
    attrdef ("arpMapping_attr2", IPV4)));

  AddRelationWithKeys (ARPREPLY, attrdeflist (
    attrdef ("arpReply_attr2", IPV4),
    attrdef ("arpReply_attr3", STR),
    attrdef ("arpReply_attr4", IPV4),
    attrdef ("arpReply_attr5", STR)));

  AddRelationWithKeys (ARPREQUEST, attrdeflist (
    attrdef ("arpRequest_attr2", IPV4),
    attrdef ("arpRequest_attr3", STR),
    attrdef ("arpRequest_attr4", IPV4),
    attrdef ("arpRequest_attr5", STR)));

  AddRelationWithKeys (FLOWENTRY, attrdeflist (
    attrdef ("flowEntry_attr2", STR)));

  AddRelationWithKeys (HOSTPOS, attrdeflist (
    attrdef ("hostPos_attr2", IPV4)));

  AddRelationWithKeys (LINKHST, attrdeflist (
    attrdef ("linkHst_attr3", INT32)));

  AddRelationWithKeys (LINKSWC, attrdeflist (
    attrdef ("linkSwc_attr3", INT32)));

  AddRelationWithKeys (OFCONNCTL, attrdeflist (
    attrdef ("ofconnCtl_attr2", IPV4)));

  AddRelationWithKeys (OFCONNSWC, attrdeflist (
    attrdef ("ofconnSwc_attr2", IPV4)));

}

void
SdnArp::DemuxRecv (Ptr<Tuple> tuple)
{
  RapidNetApplicationBase::DemuxRecv (tuple);

  if (IsInsertEvent (tuple, LINKHST))
    {
      Rh1Eca0Ins (tuple);
    }
  if (IsInsertEvent (tuple, ARPREQUEST))
    {
      Rh1Eca1Ins (tuple);
    }
  if (IsRecvEvent (tuple, PACKET))
    {
      Rh2Local1_eca (tuple);
    }
  if (IsRecvEvent (tuple, RH2PACKETHOST))
    {
      Rh2Local2_eca (tuple);
    }
  if (IsRecvEvent (tuple, PACKETIN))
    {
      Rc1_eca (tuple);
    }
  if (IsRecvEvent (tuple, PACKETIN))
    {
      Rc2_eca (tuple);
    }
  if (IsRecvEvent (tuple, ARPREQCTL))
    {
      Rc3_eca (tuple);
    }
  if (IsRecvEvent (tuple, ARPREQCTL))
    {
      Rc4_eca (tuple);
    }
  if (IsRecvEvent (tuple, ARPREPLYCTL))
    {
      Rc6_eca (tuple);
    }
  if (IsRecvEvent (tuple, PACKET))
    {
      Rs1_eca (tuple);
    }
  if (IsRecvEvent (tuple, PACKETOUT))
    {
      Rs2_eca (tuple);
    }
}

void
SdnArp::Rh1Eca0Ins (Ptr<Tuple> linkHst)
{
  RAPIDNET_LOG_INFO ("Rh1Eca0Ins triggered");

  Ptr<RelationBase> result;

  result = GetRelation (ARPREQUEST)->Join (
    linkHst,
    strlist ("arpRequest_attr1"),
    strlist ("linkHst_attr1"));

  result->Assign (Assignor::New ("Req",
    ValueExpr::New (Int32Value::New (1))));

  result->Assign (Assignor::New ("Type",
    ValueExpr::New (StrValue::New ("ARP"))));

  result->Assign (Assignor::New ("Dst",
    ValueExpr::New (StrValue::New ("ff:ff:ff:ff:ff"))));

  result = result->Project (
    PACKET,
    strlist ("linkHst_attr2",
      "linkHst_attr1",
      "Dst",
      "arpRequest_attr5",
      "arpRequest_attr4",
      "arpRequest_attr3",
      "arpRequest_attr2",
      "Req",
      "Type",
      "linkHst_attr2"),
    strlist ("packet_attr1",
      "packet_attr2",
      "packet_attr3",
      "packet_attr4",
      "packet_attr5",
      "packet_attr6",
      "packet_attr7",
      "packet_attr8",
      "packet_attr9",
      RN_DEST));

  Send (result);
}

void
SdnArp::Rh1Eca1Ins (Ptr<Tuple> arpRequest)
{
  RAPIDNET_LOG_INFO ("Rh1Eca1Ins triggered");

  Ptr<RelationBase> result;

  result = GetRelation (LINKHST)->Join (
    arpRequest,
    strlist ("linkHst_attr1"),
    strlist ("arpRequest_attr1"));

  result->Assign (Assignor::New ("Req",
    ValueExpr::New (Int32Value::New (1))));

  result->Assign (Assignor::New ("Type",
    ValueExpr::New (StrValue::New ("ARP"))));

  result->Assign (Assignor::New ("Dst",
    ValueExpr::New (StrValue::New ("ff:ff:ff:ff:ff"))));

  result = result->Project (
    PACKET,
    strlist ("linkHst_attr2",
      "arpRequest_attr1",
      "Dst",
      "arpRequest_attr5",
      "arpRequest_attr4",
      "arpRequest_attr3",
      "arpRequest_attr2",
      "Req",
      "Type",
      "linkHst_attr2"),
    strlist ("packet_attr1",
      "packet_attr2",
      "packet_attr3",
      "packet_attr4",
      "packet_attr5",
      "packet_attr6",
      "packet_attr7",
      "packet_attr8",
      "packet_attr9",
      RN_DEST));

  Send (result);
}

void
SdnArp::Rh2Local1_eca (Ptr<Tuple> packet)
{
  RAPIDNET_LOG_INFO ("Rh2Local1_eca triggered");

  Ptr<Tuple> result = packet;

  result = result->Project (
    RH2PACKETHOST,
    strlist ("packet_attr1",
      "packet_attr2",
      "packet_attr3",
      "packet_attr4",
      "packet_attr5",
      "packet_attr6",
      "packet_attr7",
      "packet_attr8",
      "packet_attr9",
      "packet_attr2"),
    strlist ("rh2packetHost_attr1",
      "rh2packetHost_attr2",
      "rh2packetHost_attr3",
      "rh2packetHost_attr4",
      "rh2packetHost_attr5",
      "rh2packetHost_attr6",
      "rh2packetHost_attr7",
      "rh2packetHost_attr8",
      "rh2packetHost_attr9",
      RN_DEST));

  Send (result);
}

void
SdnArp::Rh2Local2_eca (Ptr<Tuple> rh2packetHost)
{
  RAPIDNET_LOG_INFO ("Rh2Local2_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (LINKHST)->Join (
    rh2packetHost,
    strlist ("linkHst_attr1", "linkHst_attr2"),
    strlist ("rh2packetHost_attr2", "rh2packetHost_attr1"));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("rh2packetHost_attr3"),
      VarExpr::New ("rh2packetHost_attr2"))));

  result = result->Project (
    ARPREPLY,
    strlist ("rh2packetHost_attr2",
      "rh2packetHost_attr7",
      "rh2packetHost_attr6",
      "rh2packetHost_attr5",
      "rh2packetHost_attr4"),
    strlist ("arpReply_attr1",
      "arpReply_attr2",
      "arpReply_attr3",
      "arpReply_attr4",
      "arpReply_attr5"));

  Insert (result);
}

void
SdnArp::Rc1_eca (Ptr<Tuple> packetIn)
{
  RAPIDNET_LOG_INFO ("Rc1_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (OFCONNCTL)->Join (
    packetIn,
    strlist ("ofconnCtl_attr1", "ofconnCtl_attr2"),
    strlist ("packetIn_attr1", "packetIn_attr2"));

  result = result->Project (
    HOSTPOS,
    strlist ("packetIn_attr1",
      "packetIn_attr4",
      "packetIn_attr2",
      "packetIn_attr3"),
    strlist ("hostPos_attr1",
      "hostPos_attr2",
      "hostPos_attr3",
      "hostPos_attr4"));

  Insert (result);
}

void
SdnArp::Rc2_eca (Ptr<Tuple> packetIn)
{
  RAPIDNET_LOG_INFO ("Rc2_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (OFCONNCTL)->Join (
    packetIn,
    strlist ("ofconnCtl_attr1", "ofconnCtl_attr2"),
    strlist ("packetIn_attr1", "packetIn_attr2"));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("packetIn_attr9"),
      ValueExpr::New (StrValue::New ("ARP")))));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("packetIn_attr8"),
      ValueExpr::New (Int32Value::New (1)))));

  result = result->Project (
    ARPREQCTL,
    strlist ("packetIn_attr1",
      "packetIn_attr7",
      "packetIn_attr6",
      "packetIn_attr5",
      "packetIn_attr4"),
    strlist ("arpReqCtl_attr1",
      "arpReqCtl_attr2",
      "arpReqCtl_attr3",
      "arpReqCtl_attr4",
      "arpReqCtl_attr5"));

  SendLocal (result);
}

void
SdnArp::Rc3_eca (Ptr<Tuple> arpReqCtl)
{
  RAPIDNET_LOG_INFO ("Rc3_eca triggered");

  Ptr<Tuple> result = arpReqCtl;

  result = result->Project (
    ARPMAPPING,
    strlist ("arpReqCtl_attr1",
      "arpReqCtl_attr2",
      "arpReqCtl_attr3"),
    strlist ("arpMapping_attr1",
      "arpMapping_attr2",
      "arpMapping_attr3"));

  Insert (result);
}

void
SdnArp::Rc4_eca (Ptr<Tuple> arpReqCtl)
{
  RAPIDNET_LOG_INFO ("Rc4_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (ARPMAPPING)->Join (
    arpReqCtl,
    strlist ("arpMapping_attr1", "arpMapping_attr2"),
    strlist ("arpReqCtl_attr1", "arpReqCtl_attr4"));

  result = result->Project (
    ARPREPLYCTL,
    strlist ("arpReqCtl_attr1",
      "arpReqCtl_attr4",
      "arpMapping_attr3",
      "arpReqCtl_attr2",
      "arpReqCtl_attr3"),
    strlist ("arpReplyCtl_attr1",
      "arpReplyCtl_attr2",
      "arpReplyCtl_attr3",
      "arpReplyCtl_attr4",
      "arpReplyCtl_attr5"));

  SendLocal (result);
}

void
SdnArp::Rc6_eca (Ptr<Tuple> arpReplyCtl)
{
  RAPIDNET_LOG_INFO ("Rc6_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (OFCONNCTL)->Join (
    arpReplyCtl,
    strlist ("ofconnCtl_attr1"),
    strlist ("arpReplyCtl_attr1"));

  result = GetRelation (HOSTPOS)->Join (
    result,
    strlist ("hostPos_attr1", "hostPos_attr2", "hostPos_attr3"),
    strlist ("arpReplyCtl_attr1", "arpReplyCtl_attr2", "ofconnCtl_attr2"));

  result->Assign (Assignor::New ("Req",
    ValueExpr::New (Int32Value::New (2))));

  result->Assign (Assignor::New ("Type",
    ValueExpr::New (StrValue::New ("ARP"))));

  result = result->Project (
    PACKETOUT,
    strlist ("ofconnCtl_attr2",
      "arpReplyCtl_attr1",
      "hostPos_attr4",
      "arpReplyCtl_attr5",
      "arpReplyCtl_attr4",
      "arpReplyCtl_attr3",
      "arpReplyCtl_attr2",
      "Req",
      "Type",
      "ofconnCtl_attr2"),
    strlist ("packetOut_attr1",
      "packetOut_attr2",
      "packetOut_attr3",
      "packetOut_attr4",
      "packetOut_attr5",
      "packetOut_attr6",
      "packetOut_attr7",
      "packetOut_attr8",
      "packetOut_attr9",
      RN_DEST));

  Send (result);
}

void
SdnArp::Rs1_eca (Ptr<Tuple> packet)
{
  RAPIDNET_LOG_INFO ("Rs1_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (OFCONNSWC)->Join (
    packet,
    strlist ("ofconnSwc_attr1"),
    strlist ("packet_attr1"));

  result = GetRelation (LINKSWC)->Join (
    result,
    strlist ("linkSwc_attr2", "linkSwc_attr1"),
    strlist ("packet_attr2", "packet_attr1"));

  result = GetRelation (FLOWENTRY)->Join (
    result,
    strlist ("flowEntry_attr1"),
    strlist ("packet_attr1"));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("packet_attr9"),
      ValueExpr::New (StrValue::New ("ARP")))));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("flowEntry_attr3"),
      ValueExpr::New (Int32Value::New (1)))));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("flowEntry_attr4"),
      ValueExpr::New (StrValue::New ("controller")))));

  result = result->Project (
    PACKETIN,
    strlist ("ofconnSwc_attr2",
      "packet_attr1",
      "linkSwc_attr3",
      "packet_attr4",
      "packet_attr5",
      "packet_attr6",
      "packet_attr7",
      "packet_attr8",
      "packet_attr9",
      VariableNotFoundError,
      "ofconnSwc_attr2"),
    strlist ("packetIn_attr1",
      "packetIn_attr2",
      "packetIn_attr3",
      "packetIn_attr4",
      "packetIn_attr5",
      "packetIn_attr6",
      "packetIn_attr7",
      "packetIn_attr8",
      "packetIn_attr9",
      "packetIn_attr10",
      RN_DEST));

  Send (result);
}

void
SdnArp::Rs2_eca (Ptr<Tuple> packetOut)
{
  RAPIDNET_LOG_INFO ("Rs2_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (LINKSWC)->Join (
    packetOut,
    strlist ("linkSwc_attr1"),
    strlist ("packetOut_attr1"));

  result->Assign (Assignor::New ("$1",
    VarExpr::New ("linkSwc_attr2")));

  result = result->Project (
    PACKET,
    strlist ("linkSwc_attr2",
      "packetOut_attr1",
      "$1",
      "packetOut_attr4",
      "packetOut_attr5",
      "packetOut_attr6",
      "packetOut_attr7",
      "packetOut_attr8",
      "packetOut_attr9",
      "linkSwc_attr2"),
    strlist ("packet_attr1",
      "packet_attr2",
      "packet_attr3",
      "packet_attr4",
      "packet_attr5",
      "packet_attr6",
      "packet_attr7",
      "packet_attr8",
      "packet_attr9",
      RN_DEST));

  Send (result);
}

