## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('sdn-mac-learning-bcast', ['internet-stack'])
    module.source = [
        'sdn-mac-learning-bcast.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'sdn-mac-learning-bcast'
    headers.source = [
        'sdn-mac-learning-bcast.h',
        'sdn-mac-learning-bcast-helper.h',
        ]
