## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('load-balancer-learning', ['internet-stack'])
    module.source = [
        'load-balancer-learning.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'load-balancer-learning'
    headers.source = [
        'load-balancer-learning.h',
        'load-balancer-learning-helper.h',
        ]
