/* A RapidNet application. Generated by RapidNet compiler. */

#include "firewall.h"
#include <cstdlib>
#include "ns3/nstime.h"
#include "ns3/simulator.h"
#include "ns3/type-ids.h"
#include "ns3/rapidnet-types.h"
#include "ns3/rapidnet-utils.h"
#include "ns3/assignor.h"
#include "ns3/selector.h"
#include "ns3/rapidnet-functions.h"

using namespace std;
using namespace ns3;
using namespace ns3::rapidnet;
using namespace ns3::rapidnet::firewall;

const string Firewall::CONNECTION = "connection";
const string Firewall::PERFLOWRULE = "perFlowRule";
const string Firewall::PKTFROMSWITCH = "pktFromSwitch";
const string Firewall::PKTIN = "pktIn";
const string Firewall::PKTRECEIVED = "pktReceived";
const string Firewall::R2TRUSTEDCONTROLLERMEMORYSEND = "r2trustedControllerMemorysend";
const string Firewall::R5PERFLOWRULESEND = "r5perFlowRulesend";
const string Firewall::TRUSTEDCONTROLLERMEMORY = "trustedControllerMemory";
const string Firewall::TRUSTEDCONTROLLERMEMORYDELETE = "trustedControllerMemoryDelete";

NS_LOG_COMPONENT_DEFINE ("Firewall");
NS_OBJECT_ENSURE_REGISTERED (Firewall);

TypeId
Firewall::GetTypeId (void)
{
  static TypeId tid = TypeId ("ns3::rapidnet::firewall::Firewall")
    .SetParent<RapidNetApplicationBase> ()
    .AddConstructor<Firewall> ()
    ;
  return tid;
}

Firewall::Firewall()
{
  NS_LOG_FUNCTION_NOARGS ();
}

Firewall::~Firewall()
{
  NS_LOG_FUNCTION_NOARGS ();
}

void
Firewall::DoDispose (void)
{
  NS_LOG_FUNCTION_NOARGS ();

  RapidNetApplicationBase::DoDispose ();
}

void
Firewall::StartApplication (void)
{
  NS_LOG_FUNCTION_NOARGS ();

  RapidNetApplicationBase::StartApplication ();
  RAPIDNET_LOG_INFO("Firewall Application Started");
}

void
Firewall::StopApplication ()
{
  NS_LOG_FUNCTION_NOARGS ();

  RapidNetApplicationBase::StopApplication ();
  RAPIDNET_LOG_INFO("Firewall Application Stopped");
}

void
Firewall::InitDatabase ()
{
  //RapidNetApplicationBase::InitDatabase ();

  AddRelationWithKeys (CONNECTION, attrdeflist (
    attrdef ("connection_attr1", IPV4)));

  AddRelationWithKeys (PERFLOWRULE, attrdeflist (
    attrdef ("perFlowRule_attr1", IPV4),
    attrdef ("perFlowRule_attr2", IPV4),
    attrdef ("perFlowRule_attr3", INT32),
    attrdef ("perFlowRule_attr4", IPV4),
    attrdef ("perFlowRule_attr5", INT32)));

  AddRelationWithKeys (PKTIN, attrdeflist (
    attrdef ("pktIn_attr1", IPV4),
    attrdef ("pktIn_attr2", IPV4),
    attrdef ("pktIn_attr3", INT32),
    attrdef ("pktIn_attr4", IPV4)));

  AddRelationWithKeys (TRUSTEDCONTROLLERMEMORY, attrdeflist (
    attrdef ("trustedControllerMemory_attr2", IPV4),
    attrdef ("trustedControllerMemory_attr3", IPV4)));

}

void
Firewall::DemuxRecv (Ptr<Tuple> tuple)
{
  RapidNetApplicationBase::DemuxRecv (tuple);

  if (IsInsertEvent (tuple, PKTIN))
    {
      R1Eca0Ins (tuple);
    }
  if (IsRecvEvent (tuple, R2TRUSTEDCONTROLLERMEMORYSEND))
    {
      R2Eca0RemoteIns (tuple);
    }
  if (IsRecvEvent (tuple, TRUSTEDCONTROLLERMEMORYDELETE))
    {
      R2Eca0RemoteDel (tuple);
    }
  if (IsInsertEvent (tuple, PKTIN))
    {
      R2Eca0Ins (tuple);
    }
  if (IsDeleteEvent (tuple, PKTIN))
    {
      R2Eca0Del (tuple);
    }
  if (IsInsertEvent (tuple, CONNECTION))
    {
      R2Eca1Ins (tuple);
    }
  if (IsDeleteEvent (tuple, CONNECTION))
    {
      R2Eca1Del (tuple);
    }
  if (IsInsertEvent (tuple, PKTIN))
    {
      R3Eca0Ins (tuple);
    }
  if (IsInsertEvent (tuple, PERFLOWRULE))
    {
      R3Eca1Ins (tuple);
    }
  if (IsInsertEvent (tuple, PKTIN))
    {
      R4Eca0Ins (tuple);
    }
  if (IsInsertEvent (tuple, CONNECTION))
    {
      R4Eca1Ins (tuple);
    }
  if (IsRecvEvent (tuple, R5PERFLOWRULESEND))
    {
      R5ECAMat (tuple);
    }
  if (IsRecvEvent (tuple, PKTFROMSWITCH))
    {
      R5_eca (tuple);
    }
}

void
Firewall::R1Eca0Ins (Ptr<Tuple> pktIn)
{
  RAPIDNET_LOG_INFO ("R1Eca0Ins triggered");

  Ptr<Tuple> result = pktIn;

  result->Assign (Assignor::New ("Uport",
    ValueExpr::New (Int32Value::New (2))));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("pktIn_attr3"),
      ValueExpr::New (Int32Value::New (1)))));

  result = result->Project (
    PKTRECEIVED,
    strlist ("pktIn_attr4",
      "Uport",
      "pktIn_attr2",
      "pktIn_attr3",
      "pktIn_attr1",
      "pktIn_attr4"),
    strlist ("pktReceived_attr1",
      "pktReceived_attr2",
      "pktReceived_attr3",
      "pktReceived_attr4",
      "pktReceived_attr5",
      RN_DEST));

  Send (result);
}

void
Firewall::R2Eca0RemoteIns (Ptr<Tuple> r2trustedControllerMemorysend)
{
  RAPIDNET_LOG_INFO ("R2Eca0RemoteIns triggered");

  Ptr<Tuple> result = r2trustedControllerMemorysend;

  result = result->Project (
    TRUSTEDCONTROLLERMEMORY,
    strlist ("r2trustedControllerMemorysend_attr1",
      "r2trustedControllerMemorysend_attr2",
      "r2trustedControllerMemorysend_attr3"),
    strlist ("trustedControllerMemory_attr1",
      "trustedControllerMemory_attr2",
      "trustedControllerMemory_attr3"));

  Insert (result);
}

void
Firewall::R2Eca0RemoteDel (Ptr<Tuple> trustedControllerMemoryDelete)
{
  RAPIDNET_LOG_INFO ("R2Eca0RemoteDel triggered");

  Ptr<Tuple> result = trustedControllerMemoryDelete;

  result = result->Project (
    TRUSTEDCONTROLLERMEMORY,
    strlist ("trustedControllerMemoryDelete_attr1",
      "trustedControllerMemoryDelete_attr2",
      "trustedControllerMemoryDelete_attr3"),
    strlist ("trustedControllerMemory_attr1",
      "trustedControllerMemory_attr2",
      "trustedControllerMemory_attr3"));

  Delete (result);
}

void
Firewall::R2Eca0Ins (Ptr<Tuple> pktIn)
{
  RAPIDNET_LOG_INFO ("R2Eca0Ins triggered");

  Ptr<RelationBase> result;

  result = GetRelation (CONNECTION)->Join (
    pktIn,
    strlist ("connection_attr1"),
    strlist ("pktIn_attr1"));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("pktIn_attr3"),
      ValueExpr::New (Int32Value::New (1)))));

  result = result->Project (
    R2TRUSTEDCONTROLLERMEMORYSEND,
    strlist ("connection_attr2",
      "pktIn_attr1",
      "pktIn_attr4",
      "connection_attr2"),
    strlist ("r2trustedControllerMemorysend_attr1",
      "r2trustedControllerMemorysend_attr2",
      "r2trustedControllerMemorysend_attr3",
      RN_DEST));

  Send (result);
}

void
Firewall::R2Eca0Del (Ptr<Tuple> pktIn)
{
  RAPIDNET_LOG_INFO ("R2Eca0Del triggered");

  Ptr<RelationBase> result;

  result = GetRelation (CONNECTION)->Join (
    pktIn,
    strlist ("connection_attr1"),
    strlist ("pktIn_attr1"));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("pktIn_attr3"),
      ValueExpr::New (Int32Value::New (1)))));

  result = result->Project (
    TRUSTEDCONTROLLERMEMORYDELETE,
    strlist ("connection_attr2",
      "pktIn_attr1",
      "pktIn_attr4",
      "connection_attr2"),
    strlist ("trustedControllerMemoryDelete_attr1",
      "trustedControllerMemoryDelete_attr2",
      "trustedControllerMemoryDelete_attr3",
      RN_DEST));

  Send (result);
}

void
Firewall::R2Eca1Ins (Ptr<Tuple> connection)
{
  RAPIDNET_LOG_INFO ("R2Eca1Ins triggered");

  Ptr<RelationBase> result;

  result = GetRelation (PKTIN)->Join (
    connection,
    strlist ("pktIn_attr1"),
    strlist ("connection_attr1"));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("pktIn_attr3"),
      ValueExpr::New (Int32Value::New (1)))));

  result = result->Project (
    R2TRUSTEDCONTROLLERMEMORYSEND,
    strlist ("connection_attr2",
      "connection_attr1",
      "pktIn_attr4",
      "connection_attr2"),
    strlist ("r2trustedControllerMemorysend_attr1",
      "r2trustedControllerMemorysend_attr2",
      "r2trustedControllerMemorysend_attr3",
      RN_DEST));

  Send (result);
}

void
Firewall::R2Eca1Del (Ptr<Tuple> connection)
{
  RAPIDNET_LOG_INFO ("R2Eca1Del triggered");

  Ptr<RelationBase> result;

  result = GetRelation (PKTIN)->Join (
    connection,
    strlist ("pktIn_attr1"),
    strlist ("connection_attr1"));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("pktIn_attr3"),
      ValueExpr::New (Int32Value::New (1)))));

  result = result->Project (
    TRUSTEDCONTROLLERMEMORYDELETE,
    strlist ("connection_attr2",
      "connection_attr1",
      "pktIn_attr4",
      "connection_attr2"),
    strlist ("trustedControllerMemoryDelete_attr1",
      "trustedControllerMemoryDelete_attr2",
      "trustedControllerMemoryDelete_attr3",
      RN_DEST));

  Send (result);
}

void
Firewall::R3Eca0Ins (Ptr<Tuple> pktIn)
{
  RAPIDNET_LOG_INFO ("R3Eca0Ins triggered");

  Ptr<RelationBase> result;

  result = GetRelation (PERFLOWRULE)->Join (
    pktIn,
    strlist ("perFlowRule_attr4", "perFlowRule_attr3", "perFlowRule_attr2", "perFlowRule_attr1"),
    strlist ("pktIn_attr4", "pktIn_attr3", "pktIn_attr2", "pktIn_attr1"));

  result = result->Project (
    PKTRECEIVED,
    strlist ("pktIn_attr4",
      "perFlowRule_attr5",
      "pktIn_attr2",
      "pktIn_attr3",
      "pktIn_attr1",
      "pktIn_attr4"),
    strlist ("pktReceived_attr1",
      "pktReceived_attr2",
      "pktReceived_attr3",
      "pktReceived_attr4",
      "pktReceived_attr5",
      RN_DEST));

  Send (result);
}

void
Firewall::R3Eca1Ins (Ptr<Tuple> perFlowRule)
{
  RAPIDNET_LOG_INFO ("R3Eca1Ins triggered");

  Ptr<RelationBase> result;

  result = GetRelation (PKTIN)->Join (
    perFlowRule,
    strlist ("pktIn_attr4", "pktIn_attr3", "pktIn_attr2", "pktIn_attr1"),
    strlist ("perFlowRule_attr4", "perFlowRule_attr3", "perFlowRule_attr2", "perFlowRule_attr1"));

  result = result->Project (
    PKTRECEIVED,
    strlist ("perFlowRule_attr4",
      "perFlowRule_attr5",
      "perFlowRule_attr2",
      "perFlowRule_attr3",
      "perFlowRule_attr1",
      "perFlowRule_attr4"),
    strlist ("pktReceived_attr1",
      "pktReceived_attr2",
      "pktReceived_attr3",
      "pktReceived_attr4",
      "pktReceived_attr5",
      RN_DEST));

  Send (result);
}

void
Firewall::R4Eca0Ins (Ptr<Tuple> pktIn)
{
  RAPIDNET_LOG_INFO ("R4Eca0Ins triggered");

  Ptr<RelationBase> result;

  result = GetRelation (CONNECTION)->Join (
    pktIn,
    strlist ("connection_attr1"),
    strlist ("pktIn_attr1"));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("pktIn_attr3"),
      ValueExpr::New (Int32Value::New (2)))));

  result = result->Project (
    PKTFROMSWITCH,
    strlist ("connection_attr2",
      "pktIn_attr1",
      "pktIn_attr2",
      "pktIn_attr3",
      "pktIn_attr4",
      "connection_attr2"),
    strlist ("pktFromSwitch_attr1",
      "pktFromSwitch_attr2",
      "pktFromSwitch_attr3",
      "pktFromSwitch_attr4",
      "pktFromSwitch_attr5",
      RN_DEST));

  Send (result);
}

void
Firewall::R4Eca1Ins (Ptr<Tuple> connection)
{
  RAPIDNET_LOG_INFO ("R4Eca1Ins triggered");

  Ptr<RelationBase> result;

  result = GetRelation (PKTIN)->Join (
    connection,
    strlist ("pktIn_attr1"),
    strlist ("connection_attr1"));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("pktIn_attr3"),
      ValueExpr::New (Int32Value::New (2)))));

  result = result->Project (
    PKTFROMSWITCH,
    strlist ("connection_attr2",
      "connection_attr1",
      "pktIn_attr2",
      "pktIn_attr3",
      "pktIn_attr4",
      "connection_attr2"),
    strlist ("pktFromSwitch_attr1",
      "pktFromSwitch_attr2",
      "pktFromSwitch_attr3",
      "pktFromSwitch_attr4",
      "pktFromSwitch_attr5",
      RN_DEST));

  Send (result);
}

void
Firewall::R5ECAMat (Ptr<Tuple> r5perFlowRulesend)
{
  RAPIDNET_LOG_INFO ("R5ECAMat triggered");

  Ptr<Tuple> result = r5perFlowRulesend;

  result = result->Project (
    PERFLOWRULE,
    strlist ("r5perFlowRulesend_attr1",
      "r5perFlowRulesend_attr2",
      "r5perFlowRulesend_attr3",
      "r5perFlowRulesend_attr4",
      "r5perFlowRulesend_attr5"),
    strlist ("perFlowRule_attr1",
      "perFlowRule_attr2",
      "perFlowRule_attr3",
      "perFlowRule_attr4",
      "perFlowRule_attr5"));

  Insert (result);
}

void
Firewall::R5_eca (Ptr<Tuple> pktFromSwitch)
{
  RAPIDNET_LOG_INFO ("R5_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (TRUSTEDCONTROLLERMEMORY)->Join (
    pktFromSwitch,
    strlist ("trustedControllerMemory_attr1", "trustedControllerMemory_attr3", "trustedControllerMemory_attr2"),
    strlist ("pktFromSwitch_attr1", "pktFromSwitch_attr3", "pktFromSwitch_attr2"));

  result->Assign (Assignor::New ("Tport",
    ValueExpr::New (Int32Value::New (1))));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("pktFromSwitch_attr4"),
      ValueExpr::New (Int32Value::New (2)))));

  result = result->Project (
    R5PERFLOWRULESEND,
    strlist ("pktFromSwitch_attr2",
      "pktFromSwitch_attr3",
      "pktFromSwitch_attr4",
      "pktFromSwitch_attr5",
      "Tport",
      "pktFromSwitch_attr2"),
    strlist ("r5perFlowRulesend_attr1",
      "r5perFlowRulesend_attr2",
      "r5perFlowRulesend_attr3",
      "r5perFlowRulesend_attr4",
      "r5perFlowRulesend_attr5",
      RN_DEST));

  Send (result);
}

