/* A RapidNet application. Generated by RapidNet compiler. */

#ifndef FIREWALL_H
#define FIREWALL_H

#include <string>
#include <iostream>
#include "ns3/ptr.h"
#include "ns3/event-id.h"
#include "ns3/ipv4-address.h"
#include "ns3/rapidnet-header.h"
#include "ns3/relation-base.h"
#include "ns3/database.h"
#include "ns3/rapidnet-application-base.h"
#include "ns3/aggregator.h"
#include "ns3/aggwrap.h"

using namespace std;
using namespace ns3;

namespace ns3 {

class Socket;
class Packet;

namespace rapidnet {
namespace firewall {

class Firewall : public RapidNetApplicationBase
{
public:

  static TypeId GetTypeId (void);

  Firewall ();

  virtual ~Firewall ();

protected:

  virtual void DoDispose (void);

  virtual void StartApplication (void);

  virtual void StopApplication (void);

  virtual void InitDatabase (void);

  virtual void DemuxRecv (Ptr<Tuple> tuple);

};

} // namespace firewall
} // namespace rapidnet
} // namespace ns3

#endif // FIREWALL_H
