## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('firewall', ['internet-stack'])
    module.source = [
        'firewall.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'firewall'
    headers.source = [
        'firewall.h',
        'firewall-helper.h',
        ]
